version: '3'

services:
  quarto:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./website:/project/website
    ports:
      - "4001:4000"  # Changed to use port 4001 on the host
    command: quarto preview website --no-browser --host 0.0.0.0 --port 4000