services:
  - type: web
    name: tidy-tuesdays
    env: static
    buildCommand: |
      cd website
      apt-get update && apt-get install -y curl gdebi-core
      curl -s https://download1.rstudio.org/electron/focal/amd64/quarto-1.3.450-linux-amd64.deb -o quarto.deb
      gdebi -n quarto.deb
      R -e "install.packages(c('rmarkdown', 'knitr', 'dplyr', 'ggplot2', 'tidyverse', 'shiny', 'bslib', 'ggExtra', 'lubridate', 'plotly', 'maps', 'viridis', 'patchwork'), repos = 'https://cloud.r-project.org/')"
      quarto render
    staticPublishPath: ./website/_site
    pullRequestPreviewsEnabled: true
    autoDeploy: true