project:
  type: website

format:
  html: 
    css: resources/styles.css
    page-layout: article # doesn't seem to do much
    theme:
      light: cosmo
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true


website:
  title: "Tidy Tuesdays"
  navbar:
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://code.com
          - text: Report a Bug
            url:  https://bugs.com
  sidebar:
    style: "floating"
    search: true
    align: left
    collapse-level: 2
    contents:
      - section: "Tidy Tuesdays"
        contents:
      - href: index.qmd
        text: Introduction
      - section: Weekly Projects
        contents:
          - section: Week 1
            contents: 
              - href: one.qmd
              - text: One
          - section: Week 2
            contents:
              - href: two.qmd
              - text: Two
page-footer:
  center: 
    - text: "About"
      href: about.qmd
    - text: "License"
      href: license.qmd
    - text: "Trademark"
      href: trademark.qmd


# lux, darkly, cosmo