project:
  type: website
  output-dir: _site

website:
  title: "Tidy Tuesdays"
  favicon: resources/favicon.png
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Weekly Challenges"
        file: weekly_challenges/index.qmd
      - text: "About"
        file: about.qmd
    right:
      - icon: github
        href: https://github.com/yourusername/tidy-tuesdays
  page-footer:
    center:
      - text: "© 2025 Your Name"

format:
  html:
    theme: cosmo
    css: resources/styles.css
    toc: true
    page-layout: full