name: Build and Deploy to Vercel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gdebi-core
      
      - name: Install Quarto
        run: |
          curl -s https://download1.rstudio.org/electron/focal/amd64/quarto-1.3.450-linux-amd64.deb -o quarto.deb
          sudo gdebi -n quarto.deb
          rm quarto.deb
      
      - name: Install R dependencies
        run: |
          install.packages(c('rmarkdown', 'knitr', 'dplyr', 'ggplot2', 'tidyverse', 'shiny', 'bslib', 'ggExtra', 'lubridate', 'plotly', 'maps', 'viridis', 'patchwork'), repos = 'https://cloud.r-project.org/')
        shell: Rscript {0}
      
      - name: Build Quarto site
        run: |
          cd website
          quarto render
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Yes, this is the same as team ID
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'