name: Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gdebi-core libcurl4-openssl-dev libssl-dev libxml2-dev
      
      - name: Install Quarto
        run: |
          # Using a more reliable download source and specifying version
          wget -q https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.450/quarto-1.3.450-linux-amd64.deb
          sudo dpkg -i quarto-1.3.450-linux-amd64.deb
          quarto check
      
      - name: Install R dependencies
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          install.packages(c('rmarkdown', 'knitr', 'dplyr', 'ggplot2', 'tidyverse', 'shiny', 
                            'bslib', 'ggExtra', 'lubridate', 'plotly', 'maps', 'viridis', 'patchwork'))
        shell: Rscript {0}
      
      - name: Build Quarto site
        run: |
          cd website
          quarto render
      
      - name: List files for debugging
        run: |
          echo "Contents of website directory:"
          ls -la website
          echo "Contents of _site directory (if it exists):"
          ls -la website/_site || echo "Directory does not exist"
      
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: './website/_site'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 5