name: Build and Deploy Quarto Site

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggers

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for Git commits
      
      # Install system dependencies for R packages
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libfribidi-dev \
            libharfbuzz-dev \
            libjpeg-dev \
            libpng-dev \
            libtiff-dev \
            libcairo2-dev \
            pandoc \
            libicu-dev
      
      # Set up R
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      
      # Install required R packages
      - name: Install core R packages
        run: |
          install.packages(c("rmarkdown", "knitr", "dplyr", "ggplot2", "shiny", "bslib", "ggExtra"), repos = "https://cloud.r-project.org")
        shell: Rscript {0}
      
      # Try to install other packages, but don't fail if they can't be installed
      - name: Install additional R packages
        run: |
          install.packages(c("lubridate", "plotly", "maps", "viridis", "patchwork"), repos = "https://cloud.r-project.org")
        shell: Rscript {0}
        continue-on-error: true
      
      # List installed packages for debugging
      - name: List installed R packages
        run: |
          installed.packages()[,1]
        shell: Rscript {0}
      
      # Install Quarto
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.450
      
      # Render Quarto website
      - name: Render Quarto Website
        run: |
          cd website
          quarto render
      
      # Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "website/_site"  # The location of the built files
          skip_app_build: true  # We've already built the site using Quarto