name: Build and Deploy Quarto Site

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggers

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for Git commits
      
      # Set up R
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      
      # Install required R packages
      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "knitr", "dplyr", "ggplot2", "tidyverse", "shiny", "bslib", "ggExtra", "lubridate", "plotly", "maps", "viridis", "patchwork"), repos = "https://cloud.r-project.org")'
      
      # Install Quarto
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.450
      
      # Render Quarto website - this will also generate the thumbnails
      - name: Render Quarto Website
        run: |
          cd website
          quarto render
      
      # Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "website/_site"  # The location of the built files
          skip_app_build: true  # We've already built the site using Quarto