name: Build and Deploy Quarto Site

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggers

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for Git commits
      
      # Install system dependencies for R packages
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libfribidi-dev \
            libharfbuzz-dev \
            libjpeg-dev \
            libpng-dev \
            libtiff-dev \
            libcairo2-dev \
            pandoc \
            libicu-dev
      
      # Set up R
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      
      # Install all required packages
      - name: Install R packages
        run: |
          # Install individual packages
          packages <- c(
            # Core packages needed for rendering
            "rmarkdown", "knitr", "dplyr", "ggplot2", "readr", 
            "shiny", "bslib", "ggExtra",
            
            # Additional packages used in individual examples
            "lubridate", "plotly", "maps", "viridis", "patchwork"
          )
          
          # Install each package, reporting on success/failure
          results <- lapply(packages, function(pkg) {
            result <- try(install.packages(pkg, repos = "https://cloud.r-project.org"), silent = TRUE)
            return(c(package = pkg, success = !inherits(result, "try-error")))
          })
          
          # List results
          cat("Package installation results:\n")
          for (i in seq_along(results)) {
            status <- if(results[[i]][2] == "TRUE") "SUCCESS" else "FAILED"
            cat(sprintf("- %s: %s\n", results[[i]][1], status))
          }
          
          # Print installed packages
          cat("\nInstalled packages:\n")
          installed <- installed.packages()[,1]
          cat(paste(installed, collapse = ", "), "\n")
        shell: Rscript {0}
      
      # Install Quarto
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.450
      
      # Render Quarto website
      - name: Render Quarto Website
        run: |
          cd website
          quarto render
      
      # Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "website/_site"  # The location of the built files
          skip_app_build: true  # We've already built the site using Quarto