name: Render Quarto Projects

on:
  push:
    paths:
      - 'weekly_challenges/week*_quarto/app.qmd'

jobs:
  build-and-render:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install Quarto
      run: |
        wget -qO- "https://github.com/quarto-dev/quarto-cli/releases/download/v0.9.534/quarto-0.9.534-linux-amd64.deb" > quarto.deb
        sudo dpkg -i quarto.deb
        rm quarto.deb

    - name: Render Quarto Documents
      run: |
        cd weekly_challenges
        mkdir rendered_output  # Create a directory to store rendered files
        for dir in */; do
          if [[ $dir == *"_quarto/" ]]; then
            cd "$dir"
            quarto render --to html --output-dir ../../rendered_output/${dir%_quarto/}
            cd ../..
          fi
        done

    - name: Upload Rendered Files as Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: rendered-html
        path: weekly_challenges/rendered_output/
