name: Update Quarto Configuration

on:
  push:
    branches:
      - main
    paths:
      - 'weekly_challenges/**'
      - '.github/scripts/update_quarto.py'

jobs:
  update-quarto-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Update Quarto Configuration File
        run: python .github/scripts/update_quarto.py

      - name: Commit and Push Changes
        run: |
          git config --global user.email "admin@oneequalsone.uk"
          git config --global user.name "one3qualsone"
          git add website/_quarto.yml
          git commit -m 'Update _quarto.yml with latest weekly challenges'
          git push