name: Deploy Shiny Apps

on:
  push:
    paths:
      - 'weekly_challenges/week*_shiny/app.r'
      - 'Dockerfile'  # If your Shiny Dockerfile might change

jobs:
  deploy-shiny-app:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and Push Docker Image
      run: |
        # Build your Docker image
        docker build -t your-dockerhub-username/my-shiny-server-image:latest .
        
        # Log in to DockerHub (or your container registry)
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u your-dockerhub-username --password-stdin
        
        # Push the image to DockerHub (or your container registry)
        docker push your-dockerhub-username/my-shiny-server-image:latest

    - name: Update Kubernetes Deployment
      run: |
        # This step assumes you have a Kubernetes cluster and kubectl set up
        # Update the Kubernetes deployment to use the new image
        kubectl set image deployment/my-shiny-server-deployment my-shiny-server=my-dockerhub-username/my-shiny-server-image:latest
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
